# Get a default list
GET http://localhost:3000/todo HTTP/1.1

###
# Create a CustomTodoList Dynamically
GET http://localhost:3000/Home HTTP/1.1

###

# Create a todo to a list dynamically
POST http://localhost:3000/Home HTTP/1.1
Content-Type: application/json

{
  "title": "Learn React"
}

###

# Get a Todo from the a dynamic list
GET http://localhost:3000/Home/6336c8feb23a30b28afa549b HTTP/1.1

###

# Delete a Todo from dynamic list
DELETE http://localhost:3000/Home/6336c893e114e02dca5dde7b HTTP/1.1
